### ISSUE TITLE
Implementation of "Fast and Accurate 3D Registration from Line Intersection Constraints"

### ISSUE THREAD

**Issue by juanmed** [3DVisionISR/3DMinRegLineIntersect#3]
Hello. First, thank you for making an implementation of your publications available here. I found your work through your recent paper:

Fast and Accurate 3D Registration from Line Intersection Constraints, from
A. Mateus, S. Ranade, S. Ramalingam, and P. Miraldo, International Journal Computer Vision (IJCV), 2023

which I read with great interest. Through your webpage, it seems that the code implementation for this paper should be in this repository. I was unable to find references  to it, and wanted to kindly ask if you will be uploading it in the near future? 

Thanks again,

**Comment by pmiraldo** [comment]
Hi Juan,

Thank you for your message. If I remember correctly, what we have now are the CVPR solvers.
We are late cleaning up the code -- it will be done soon. In the meantime, if you are interested in a particular solver, you can send me an email. I can provide you with the code.

Thanks,
Pedro

**Comment by pmiraldo** [comment]
It should be done now.
Let us know if you find any issue.

Thanks again,
Pedro
